### ISSUE TITLE
[FEATURE] Docker image

### ISSUE THREAD

**Issue by altokarev** [slackapi/definition-app#25]
### Description

Hey @colmdoyle! 👋

Nice app! Thank you!

If you could provide us with a docker image it would be great.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by colmdoyle** [comment]
https://github.com/slackapi/definition-app/packages/389813
